import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Toolsbar from "@/components/Toolsbar";
import Header from "@/components/Header";
import Explorer from "@/components/Explorer";
import Footer from "@/components/Footer";
import Headercontent from "../components/Headercontent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kimia Rahimi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <div className="grid grid-cols-custom grid-rows-custom h-full">
          <div className="col-span-3">
            <Header />
          </div>
          <Toolsbar />
          <Explorer />

          <div className="grid grid-row-2 overflow-hidden h-full">
            <div>
              <Headercontent />
            </div>
            <div
              className=" overflow-y-auto h-full "
            >
              {children}
            </div>
          </div>
          <div className="col-span-3">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
